blank_words_to_avoid = ['what', 'when', 'where', 'which', 'whom', 'whose', 'does', 'will', 'would',
                        'could', 'should', 'shall', 'might', 'were', 'have', 'been', 'from', 'about',
                        'with', 'that', 'this', 'these', 'those', 'there', 'then', 'than', 'their',
                        'they', 'them', 'being', 'into', 'onto', 'down', 'over', 'under', 'between',
                        'among', 'through', 'after', 'before', 'since', 'while', 'until', 'till',
                        'though', 'although', 'because', 'unless', 'whether', 'either', 'neither',
                        'both', 'each', 'every', 'some', 'such', 'only', 'just', 'even', 'also', 'very',
                        'much', 'many', 'fewer', 'fewest', 'most', 'more', 'less', 'least', 'other',
                        'another', 'another', 'your', 'theirs', 'yours', 'mine', 'ours', 'myself',
                        'yourself', 'himself', 'herself', 'itself', 'ourselves', 'themselves',
                        'yourselves', 'weren\'t', 'wasn\'t', 'isn\'t', 'aren\'t', 'ain\'t', 'don\'t',
                        'doesn\'t', 'didn\'t', 'can\'t', 'couldn\'t', 'shouldn\'t', 'wouldn\'t',
                        'won\'t', 'hasn\'t', 'haven\'t', 'hadn\'t', 'mustn\'t', 'needn\'t', 'mightn\'t',
                        'shan\'t', 'oughtn\'t', 'daren\'t', 'mayn\'t', 'mustn\'ve', 'could\'ve',
                        'should\'ve', 'would\'ve', 'might\'ve', 'biggest', 'largest', 'smallest',
                        'tallest', 'shortest', 'longest', 'best', 'worst', 'most', 'least', 'greatest',
                        'highest', 'lowest', 'fastest', 'slowest', 'quickest', 'easiest', 'hardest',
                        'most', 'bigger', 'larger', 'smaller', 'taller', 'shorter', 'longer', 'better',
                        'worse', 'greater', 'higher', 'lower', 'faster', 'slower', 'quicker', 'easier',
                        'harder', 'more', 'less', 'greatest', 'call', 'called', 'calls', 'calling',
                        'name', 'named', 'names', 'naming', 'name', 'named', 'names', 'naming', 'say',
                        'said', 'says', 'saying', 'tell', 'told', 'tells', 'telling', 'ask', 'asked',
                        'asks', 'asking', 'answer', 'answered', 'answers', 'answering', 'question',
                        'once', 'twice', 'cannot', 'think', 'thought', 'thinks', 'thinking', 'know',
                        'knew', 'knows', 'knowing', 'questioned', 'take', 'took', 'takes', 'taking',
                        'taken', 'make', 'made', 'makes', 'making', 'post', 'posts', 'kind', 'kinds',
                        'sort', 'like', 'likes', 'liked', 'liking', 'love', 'loves', 'loved', 'loving',
                        'hate', 'hates', 'hated', 'hating', 'prefer', 'prefers', 'preferred', 'hear',
                        'heard', 'hears', 'hearing', 'happen', 'happened', 'happens', 'happening',
                        'have', 'having', 'having', 'give', 'gave', 'gives', 'giving', 'given', 'gets',
                        'getting', 'gotten', 'goes', 'going', 'went', 'gone', 'used', 'uses', 'using']
