true_or_false_animals = {
    "1": {"category": "animals", "statement": "Jaguars are ____ cats.", "answer": "solitary", "options": ["solitary", "social"]},
    "2": {"category": "animals", "statement": "The bat is the only ____ that can fly.", "answer": "mammal", "options": ["mammal", "reptile"]},
    "3": {"category": "animals", "statement": "A lion's roar can be heard up to eight ____ away.", "answer": "kilometres", "options": ["kilometres", "miles"]},
    "4": {"category": "animals", "statement": "The heart of a shrimp is located in its ____.", "answer": "head", "options": ["head", "abdomen"]},
    "5": {"category": "animals", "statement": "A tarantula can live without food for more than two ____.", "answer": "years", "options": ["years", "months"]},
    "6": {"category": "animals", "statement": "A wombat's poop is ____-shaped.", "answer": "cube", "options": ["cube", "cone"]},
    "7": {"category": "animals", "statement": "A rhinoceros' horn is made of ____.", "answer": "keratin", "options": ["keratin", "ivory"]},
    "8": {"category": "animals", "statement": "The blue whale is the largest ____ to ever live on Earth.", "answer": "mammal", "options": ["mammal", "fish"]},
    "9": {"category": "animals", "statement": "The platypus is the only mammal to have ____ spurs.", "answer": "venomous", "options": ["venomous", "sharp"]},
    "10": {"category": "animals", "statement": "Giant otters can grow to be up to ____ metres long.", "answer": "1.8", "options": ["1.8", "2.5"]},
    "11": {"category": "animals", "statement": "The ____ is the only bird that can fly backwards.", "answer": "hummingbird", "options": ["hummingbird", "parrot"]},
    "12": {"category": "animals", "statement": "The poison dart frog is found in the rainforests of ____.", "answer": "South America", "options": ["South America", "Africa"]},
    "13": {"category": "animals", "statement": "Hyenas once lived in ____.", "answer": "Europe", "options": ["Europe", "Australia"]},
    "14": {"category": "animals", "statement": "Smilodon is the scientific name of the ____.", "answer": "sabre-toothed cat", "options": ["sabre-toothed cat", "dire wolf"]},
    "15": {"category": "animals", "statement": "The tarantula hawk is a kind of ____ that preys on tarantulas.", "answer": "wasp", "options": ["wasp", "bird"]},
    "16": {"category": "animals", "statement": "The only mammal capable of true flight is the ____.", "answer": "bat", "options": ["bat", "squirrel"]},
    "17": {"category": "animals", "statement": "The largest type of 'big cat' in the world is the ____.", "answer": "tiger", "options": ["tiger", "lion"]},
    "18": {"category": "animals", "statement": "An adult male elephant is called a ____.", "answer": "bull", "options": ["bull", "sergeant"]},
    "19": {"category": "animals", "statement": "A group of crows is known as a ____.", "answer": "murder", "options": ["murder", "flock"]},
    "20": {"category": "animals", "statement": "The only animal with four knees is the ____.", "answer": "elephant", "options": ["elephant", "giraffe"]},
    "21": {"category": "animals", "statement": "The largest bird in the world is the ____.", "answer": "ostrich", "options": ["ostrich", "eagle"]},
    "22": {"category": "animals", "statement": "The world's largest reptile is the ____.", "answer": "saltwater crocodile", "options": ["saltwater crocodile", "komodo dragon"]},
    "23": {"category": "animals", "statement": "The mammal known for having the longest lifespan is the ____.", "answer": "bowhead whale", "options": ["bowhead whale", "elephant"]},
    "24": {"category": "animals", "statement": "A male duck is called a ____.", "answer": "drake", "options": ["drake", "gander"]},
    "25": {"category": "animals", "statement": "The Komodo dragon is a type of ____.", "answer": "lizard", "options": ["lizard", "snake"]},
    "26": {"category": "animals", "statement": "The largest species of penguin is the ____ penguin.", "answer": "emperor", "options": ["emperor", "king"]},
    "27": {"category": "animals", "statement": "The main diet of a koala is ____ leaves.", "answer": "eucalyptus", "options": ["eucalyptus", "bamboo"]},
    "28": {"category": "animals", "statement": "The largest species of shark is the ____ shark.", "answer": "whale", "options": ["whale", "hammerhead"]},
    "29": {"category": "animals", "statement": "A group of kangaroos is known as a ____.", "answer": "mob", "options": ["mob", "pack"]},
    "30": {"category": "animals", "statement": "The smallest breed of dog is the ____.", "answer": "Chihuahua", "options": ["Chihuahua", "Dachshund"]},
    "31": {"category": "animals", "statement": "The long-necked marine reptile that lived during the dinosaur era is the ____.", "answer": "plesiosaur", "options": ["plesiosaur", "mosasaur"]},
    "32": {"category": "animals", "statement": "The national bird of the United States is the ____.", "answer": "bald eagle", "options": ["bald eagle", "turkey"]},
    "33": {"category": "animals", "statement": "The largest species of pinniped is the ____.", "answer": "elephant seal", "options": ["elephant seal", "sea lion"]},
    "34": {"category": "animals", "statement": "The fastest marine animal is the ____.", "answer": "black marlin", "options": ["black marlin", "bottlenose dolphin"]},
    "35": {"category": "animals", "statement": "The world's smallest mammal is the ____.", "answer": "bumblebee bat", "options": ["bumblebee bat", "pygmy shrew"]},
    "36": {"category": "animals", "statement": "The slow-moving reptile known for its algae-covered shell is the ____.", "answer": "turtle", "options": ["turtle", "tortoise"]},
    "37": {"category": "animals", "statement": "The bird known for its distinctive laughing call is the ____.", "answer": "kookaburra", "options": ["kookaburra", "parrot"]},
    "38": {"category": "animals", "statement": "The smallest breed of horse is the ____.", "answer": "Falabella", "options": ["Falabella", "Shetland pony"]},
    "39": {"category": "animals", "statement": "The fastest land bird is the ____.", "answer": "ostrich", "options": ["ostrich", "emu"]},
    "40": {"category": "animals", "statement": "The venomous snake native to North America with a distinctive red, yellow, and black pattern is the ____.", "answer": "coral snake", "options": ["coral snake", "rattlesnake"]},
    "41": {"category": "animals", "statement": "The flightless bird native to New Zealand is the ____.", "answer": "kiwi", "options": ["kiwi", "emu"]},
    "42": {"category": "animals", "statement": "The smallest species of owl is the ____.", "answer": "elf owl", "options": ["elf owl", "Eurasian pygmy owl"]},
    "43": {"category": "animals", "statement": "The largest species of octopus is the ____.", "answer": "giant Pacific octopus", "options": ["giant Pacific octopus", "blue-ringed octopus"]},
    "44": {"category": "animals", "statement": "The rodent known for its cheek pouches is the ____.", "answer": "hamster", "options": ["hamster", "guinea pig"]},
    "45": {"category": "animals", "statement": "The largest species of kangaroo is the ____ kangaroo.", "answer": "red", "options": ["red", "gray"]},
    "46": {"category": "animals", "statement": "The marine mammal known for its spiraled tusk is the ____.", "answer": "narwhal", "options": ["narwhal", "beluga whale"]},
    "47": {"category": "animals", "statement": "The largest species of antelope is the ____.", "answer": "eland", "options": ["eland", "kudu"]},
    "48": {"category": "animals", "statement": "The largest species of bear is the ____.", "answer": "polar bear", "options": ["polar bear", "brown bear"]},
    "49": {"category": "animals", "statement": "The largest species of deer is the ____.", "answer": "moose", "options": ["moose", "elk"]},
    "50": {"category": "animals", "statement": "Chinchillas are native to ____.", "answer": "South America", "options": ["South America", "Africa"]},
    "51": {"category": "animals", "statement": "Lynxes can be found in ____.", "answer": "the northern hemisphere", "options": ["the northern hemisphere", "the northern and southern hemisphere"]},
    "52": {"category": "animals", "statement": "The puma is also known as the ____.", "answer": "mountain lion", "options": ["mountain lion", "vampire cat"]},
    "53": {"category": "animals", "statement": "The main predator of penguins is the ____.", "answer": "leopard seal", "options": ["leopard seal", "killer whale"]},
    "54": {"category": "animals", "statement": "A newborn kangaroo is about the size of a ____.", "answer": "jellybean", "options": ["jellybean", "grape"]},
    "55": {"category": "animals", "statement": "The hyrax is more closely related to ____ than mice.", "answer": "elephants", "options": ["elephants", "hippopotamuses"]},
    "56": {"category": "animals", "statement": "Camels first evolved in ____.", "answer": "North America", "options": ["North America", "Asia"]},
    "57": {"category": "animals", "statement": "Horses can ____ like humans.", "answer": "sweat", "options": ["sweat", "cry"]},
    "58": {"category": "animals", "statement": "The Asian giant hornet is the world's largest ____.", "answer": "wasp", "options": ["wasp", "bee"]},
    "59": {"category": "animals", "statement": "The albatross is a type of ____.", "answer": "seabird", "options": ["seabird", "shorebird"]},
    "60": {"category": "animals", "statement": "Dolphins sleep with ____ open.", "answer": "one eye", "options": ["one eye", "both eyes"]},
    "61": {"category": "animals", "statement": "Honeybees dance to tell other bees where ____ is.", "answer": "food", "options": ["food", "water"]},
    "62": {"category": "animals", "statement": "The newt is a type of ____.", "answer": "amphibian", "options": ["amphibian", "reptile"]},
    "63": {"category": "animals", "statement": "The coconut crab is the world's largest ____.", "answer": "land arthropod", "options": ["land arthropod", "land amphibian"]},
    "64": {"category": "animals", "statement": "The largest species of salamander is the ____.", "answer": "Chinese giant salamander", "options": ["Chinese giant salamander", "hellbender"]},
    "65": {"category": "animals", "statement": "The largest species of frog is the ____.", "answer": "goliath frog", "options": ["goliath frog", "bullfrog"]},
    "66": {"category": "animals", "statement": "Male emperor penguins are known for ____ their eggs.", "answer": "incubating", "options": ["incubating", "abandoning"]},
    "67": {"category": "animals", "statement": "The largest species of sea turtle is the ____.", "answer": "leatherback", "options": ["leatherback", "green"]},
    "68": {"category": "animals", "statement": "Wolverines are found in ____.", "answer": "the northern hemisphere", "options": ["the northern hemisphere", "the southern hemisphere"]},
    "69": {"category": "animals", "statement": "The largest species of seal is the ____.", "answer": "southern elephant seal", "options": ["southern elephant seal", "northern elephant seal"]},
    "70": {"category": "animals", "statement": "The ____ is the only marsupial native to North America.", "answer": "opossum", "options": ["opossum", "wombat"]},
    "71": {"category": "animals", "statement": "The largest species of squid is the ____.", "answer": "colossal squid", "options": ["colossal squid", "empire squid"]},
    "72": {"category": "animals", "statement": "Some cats wake their owners up early because they think their owners need to ____.", "answer": "hunt", "options": ["hunt", "eat"]},
    "73": {"category": "animals", "statement": "The ____ eats its own poop.", "answer": "rabbit", "options": ["rabbit", "guinea pig"]},
    "74": {"category": "animals", "statement": "Penguins are native to ____.", "answer": "the southern hemisphere", "options": ["the southern hemisphere", "all polar regions"]},
    "75": {"category": "animals", "statement": "Cheetah cubs have ____ on their backs.", "answer": "manes", "options": ["manes", "spots"]},
    "76": {"category": "animals", "statement": "Baby tapirs look like ____.", "answer": "watermelons", "options": ["watermelons", "dragonfruits"]},
    "77": {"category": "animals", "statement": "The red fox ____ to Australia.", "answer": "is not native", "options": ["is not native", "is native"]},
    "78": {"category": "animals", "statement": "The Scottish wildcat is ____.", "answer": "critically endangered", "options": ["critically endangered", "extinct"]},
    "79": {"category": "animals", "statement": "The bee dance is known as the ____.", "answer": "waggle dance", "options": ["waggle dance", "wobble dance"]},
    "80": {"category": "animals", "statement": "Owls have ____.", "answer": "facial disks", "options": ["facial disks", "horns"]},
    "81": {"category": "animals", "statement": "Octopuses have ____.", "answer": "three hearts", "options": ["three hearts", "four hearts"]},
    "82": {"category": "animals", "statement": "Dolphins each have their own ____.", "answer": "signature whistle", "options": ["signature whistle", "signature click"]},
    "83": {"category": "animals", "statement": "Koalas have ____ like human fingerprints.", "answer": "fingerprints", "options": ["fingerprints", "pawprints"]},
    "84": {"category": "animals", "statement": "Male ____ give birth.", "answer": "seahorses", "options": ["seahorses", "sea turtles"]},
    "85": {"category": "animals", "statement": "Scorpions belong to the class ____.", "answer": "arachnida", "options": ["arachnida", "insecta"]},
    "86": {"category": "animals", "statement": "Clownfish can change their ____.", "answer": "gender", "options": ["gender", "color"]},
    "87": {"category": "animals", "statement": "Humpback whales are known for their ____.", "answer": "songs", "options": ["songs", "dances"]},
    "88": {"category": "animals", "statement": "The only sweat glands that dogs have are on their ____.", "answer": "paws", "options": ["paws", "noses"]},
    "89": {"category": "animals", "statement": "Naked mole rats are immune to ____.", "answer": "cancer", "options": ["cancer", "aging"]},
    "90": {"category": "animals", "statement": "Bees can recognize ____.", "answer": "human faces", "options": ["human faces", "human voices"]},
    "91": {"category": "animals", "statement": "Butterflies taste with their ____.", "answer": "feet", "options": ["feet", "antennae"]},
    "92": {"category": "animals", "statement": "Sea otters use ____ to crack open shells.", "answer": "rocks", "options": ["rocks", "sticks"]},
    "93": {"category": "animals", "statement": "Albatrosses can sleep while ____.", "answer": "flying", "options": ["flying", "swimming"]},
    "94": {"category": "animals", "statement": "An owl can see its prey up to ____ away.", "answer": "two miles", "options": ["two miles", "eight miles"]},
    "95": {"category": "animals", "statement": "The terror bird was a large, flightless bird that lived in ____.", "answer": "South America", "options": ["South America", "Africa"]},
    "96": {"category": "animals", "statement": "Cheetah cubs look like ____.", "answer": "honey badgers", "options": ["honey badgers", "hyenas"]},
    "97": {"category": "animals", "statement": "Cats and dogs can make their own ____.", "answer": "vitamin C", "options": ["vitamin C", "vitamin D"]},
    "98": {"category": "animals", "statement": "Puffins are also known as ____.", "answer": "sea parrots", "options": ["sea parrots", "sea penguins"]},
    "99": {"category": "animals", "statement": "Pufferfish ____ when they are threatened.", "answer": "inflate", "options": ["inflate", "deflate"]},
    "100": {"category": "animals", "statement": "Coyotes sometimes mate with ____.", "answer": "wolves", "options": ["wolves", "foxes"]}
}


true_or_false_countries = {
    "1": {"category": "countries", "statement": "The country with the most islands is ____.", "answer": "Sweden", "options": ["Sweden", "Indonesia"]},
    "2": {"category": "countries", "statement": "The country with the most active volcanoes is ____.", "answer": "Indonesia", "options": ["Indonesia", "Japan"]},
    "3": {"category": "countries", "statement": "The country with the most time zones is ____.", "answer": "France", "options": ["France", "Russia"]},
    "4": {"category": "countries", "statement": "The country with the most national parks is ____.", "answer": "Australia", "options": ["Australia", "United States"]},
    "5": {"category": "countries", "statement": "Finland has the most ____ per capita.", "answer": "saunas", "options": ["saunas", "ski resorts"]},
    "6": {"category": "countries", "statement": "Mexico has the most ____ in the world.", "answer": "taxis", "options": ["taxis", "hotels"]},
    "7": {"category": "countries", "statement": "South Korea is an ____.", "answer": "MEDC", "options": ["MEDC", "LEDC"]},
    "8": {"category": "countries", "statement": "India's population has recently surpassed ____.", "answer": "China", "options": ["China", "United States"]},
    "9": {"category": "countries", "statement": "The smallest country in the world is ____.", "answer": "Vatican City", "options": ["Vatican City", "Monaco"]},
    "10": {"category": "countries", "statement": "The average person in ____ drinks the most coffee in the world.", "answer": "Finland", "options": ["Finland", "Denmark"]},
    "11": {"category": "countries", "statement": "The world's largest producer of coffee is ____.", "answer": "Brazil", "options": ["Brazil", "Vietnam"]},
    "12": {"category": "countries", "statement": "The world's largest producer of tea is ____.", "answer": "China", "options": ["China", "India"]},
    "13": {"category": "countries", "statement": "The world's largest producer of bananas is ____.", "answer": "India", "options": ["India", "China"]},
    "14": {"category": "countries", "statement": "The world's largest producer of rice is ____.", "answer": "China", "options": ["China", "India"]},
    "15": {"category": "countries", "statement": "The world's largest producer of wheat is ____.", "answer": "China", "options": ["China", "India"]},
    "16": {"category": "countries", "statement": "The world's largest producer of potatoes is ____.", "answer": "China", "options": ["China", "India"]},
    "17": {"category": "countries", "statement": "The world's largest producer of tomatoes is ____.", "answer": "China", "options": ["China", "India"]},
    "18": {"category": "countries", "statement": "Bolivia is a ____ country.", "answer": "landlocked", "options": ["landlocked", "coastal"]},
    "19": {"category": "countries", "statement": "The world's largest producer of oranges is ____.", "answer": "Brazil", "options": ["Brazil", "China"]},
    "20": {"category": "countries", "statement": "The world's rainiest country is ____.", "answer": "Colombia", "options": ["Colombia", "Indonesia"]},
    "21": {"category": "countries", "statement": "Turkey is a ____ country.", "answer": "transcontinental", "options": ["transcontinental", "continental"]},
    "22": {"category": "countries", "statement": "The national language of Pakistan is ____.", "answer": "Urdu", "options": ["Urdu", "Hindi"]},
    "23": {"category": "countries", "statement": "The national language of India is ____.", "answer": "Hindi", "options": ["Hindi", "Urdu"]},
    "24": {"category": "countries", "statement": "The world's largest producer of milk is ____.", "answer": "India", "options": ["India", "United States"]},
    "25": {"category": "countries", "statement": "The United States is a ____ country.", "answer": "federal", "options": ["federal", "unitary"]},
    "26": {"category": "countries", "statement": "The United Kingdom is a ____ country.", "answer": "unitary", "options": ["unitary", "federal"]},
    "27": {"category": "countries", "statement": "Most police officers in ____ do not carry guns.", "answer": "the United Kingdom", "options": ["the United Kingdom", "Germany"]},
    "28": {"category": "countries", "statement": "Italian people do not usually eat ____.", "answer": "pineapple pizza", "options": ["pineapple pizza", "pepperoni pizza"]},
    "29": {"category": "countries", "statement": "The national animal of Scotland is the ____.", "answer": "unicorn", "options": ["unicorn", "dragon"]},
    "30": {"category": "countries", "statement": "The national animal of Wales is the ____.", "answer": "dragon", "options": ["dragon", "unicorn"]},
    "31": {"category": "countries", "statement": "Germany is famous for its ____.", "answer": "beer", "options": ["beer", "wine"]},
    "32": {"category": "countries", "statement": "The national animal of France is the ____.", "answer": "rooster", "options": ["rooster", "lion"]},
    "33": {"category": "countries", "statement": "The national animal of the United States is the ____.", "answer": "bald eagle", "options": ["bald eagle", "bison"]},
    "34": {"category": "countries", "statement": "The national animal of Canada is the ____.", "answer": "beaver", "options": ["beaver", "moose"]},
    "35": {"category": "countries", "statement": "The national animal of Australia is the ____.", "answer": "kangaroo", "options": ["kangaroo", "koala"]},
    "36": {"category": "countries", "statement": "The national animal of New Zealand is the ____.", "answer": "kiwi", "options": ["kiwi", "moa"]},
    "37": {"category": "countries", "statement": "The national animal of China is the ____.", "answer": "giant panda", "options": ["giant panda", "red panda"]},
    "38": {"category": "countries", "statement": "Denmark is famous for its ____.", "answer": "pastries", "options": ["pastries", "chocolate"]},
    "39": {"category": "countries", "statement": "Namibia is a ____ country.", "answer": "desert", "options": ["desert", "tropical"]},
    "40": {"category": "countries", "statement": "The national animal of Russia is the ____.", "answer": "brown bear", "options": ["brown bear", "polar bear"]},
    "41": {"category": "countries", "statement": "The national animal of Brazil is the ____.", "answer": "jaguar", "options": ["jaguar", "cougar"]},
    "42": {"category": "countries", "statement": "The national animal of Argentina is the ____.", "answer": "puma", "options": ["puma", "jaguar"]},
    "43": {"category": "countries", "statement": "The national animal of Mexico is the ____.", "answer": "golden eagle", "options": ["golden eagle", "jaguar"]},
    "44": {"category": "countries", "statement": "Kenya has the most ____ in the world.", "answer": "marathons", "options": ["marathons", "safari parks"]},
    "45": {"category": "countries", "statement": "Madagascar is a ____ country.", "answer": "tropical", "options": ["tropical", "desert"]},
    "46": {"category": "countries", "statement": "Slovenia is a ____ country.", "answer": "mountainous", "options": ["mountainous", "flat"]},
    "47": {"category": "countries", "statement": "The most visited country in the world is ____.", "answer": "France", "options": ["France", "United States"]},
    "48": {"category": "countries", "statement": "The country with the most UNESCO World Heritage Sites is ____.", "answer": "Italy", "options": ["Italy", "China"]},
    "49": {"category": "countries", "statement": "Belgium is famous for its ____.", "answer": "chocolate", "options": ["chocolate", "bread"]},
    "50": {"category": "countries", "statement": "Austria is famous for its ____.", "answer": "pastries", "options": ["pastries", "chocolate"]},
    "51": {"category": "countries", "statement": "Kazakhstan is a ____ country.", "answer": "landlocked", "options": ["landlocked", "coastal"]},
    "52": {"category": "countries", "statement": "Mongolia is well-known for its ____.", "answer": "horses", "options": ["horses", "cows"]},
    "53": {"category": "countries", "statement": "Chile has the most ____ in South America.", "answer": "volcanoes", "options": ["volcanoes", "rainforests"]},
    "54": {"category": "countries", "statement": "Brazil is ____ in South American that speaks Portuguese.", "answer": "the only country", "options": ["the only country", "one of two countries"]},
    "55": {"category": "countries", "statement": "Guatemala is located in ____.", "answer": "Central America", "options": ["Central America", "South America"]},
    "56": {"category": "countries", "statement": "The country with the oldest living civilization is ____.", "answer": "China", "options": ["China", "India"]},
    "57": {"category": "countries", "statement": "Thailand is well-known for its ____.", "answer": "temples", "options": ["temples", "castles"]},
    "58": {"category": "countries", "statement": "The country with the most castles is ____.", "answer": "Germany", "options": ["Germany", "United Kingdom"]},
    "59": {"category": "countries", "statement": "Malaysia is famous for its ____.", "answer": "rainforests", "options": ["rainforests", "mountains"]},
    "60": {"category": "countries", "statement": "The country with the most skyscrapers is ____.", "answer": "China", "options": ["China", "United States"]},
    "61": {"category": "countries", "statement": "The country with the most pyramids is ____.", "answer": "Sudan", "options": ["Sudan", "Egypt"]},
    "62": {"category": "countries", "statement": "Poland is well-known for its ____.", "answer": "pierogies", "options": ["pierogies", "stews"]},
    "63": {"category": "countries", "statement": "Oman is a ____ country.", "answer": "desert", "options": ["desert", "tropical"]},
    "64": {"category": "countries", "statement": "Police officers in ____ do not usually carry guns.", "answer": "Iceland", "options": ["Iceland", "Finland"]},
    "65": {"category": "countries", "statement": "The national animal of Iceland is the ____.", "answer": "gyrfalcon", "options": ["gyrfalcon", "polar bear"]},
    "66": {"category": "countries", "statement": "Slovenia is known for its ____.", "answer": "caves", "options": ["caves", "rivers"]},
    "67": {"category": "countries", "statement": "South African food is known for its ____.", "answer": "meat", "options": ["meat", "fish"]},
    "68": {"category": "countries", "statement": "Argentina is well-known for being the birthplace of ____.", "answer": "tango", "options": ["tango", "salsa"]},
    "69": {"category": "countries", "statement": "Australian people do not usually eat ____.", "answer": "kangaroo", "options": ["kangaroo", "pork"]},
    "70": {"category": "countries", "statement": "South Korea is well-known for its ____.", "answer": "technology", "options": ["technology", "laptop computers"]},
    "71": {"category": "countries", "statement": "The country with the most underground transit systems is ____.", "answer": "China", "options": ["China", "United States"]},
    "72": {"category": "countries", "statement": "The country with the most airports is ____.", "answer": "United States", "options": ["United States", "China"]},
    "73": {"category": "countries", "statement": "Vietnam has the most ____ in the world.", "answer": "motorcycles", "options": ["motorcycles", "bicycles"]},
    "74": {"category": "countries", "statement": "Tanabata is a festival celebrated in ____.", "answer": "Japan", "options": ["Japan", "China"]},
    "75": {"category": "countries", "statement": "Golden Week is a festival celebrated in ____.", "answer": "China", "options": ["China", "Japan"]},
    "76": {"category": "countries", "statement": "People in ____ do not usually eat sushi.", "answer": "China", "options": ["China", "Japan"]},
    "77": {"category": "countries", "statement": "Ethiopia is a ____ country.", "answer": "landlocked", "options": ["landlocked", "coastal"]},
    "78": {"category": "countries", "statement": "The national animal of Ethiopia is the ____.", "answer": "lion", "options": ["lion", "tiger"]},
    "79": {"category": "countries", "statement": "Micronesia is located in ____.", "answer": "Oceania", "options": ["Oceania", "Asia"]},
    "80": {"category": "countries", "statement": "Liechtenstein is ____ in Europe.", "answer": "the smallest country", "options": ["the smallest country", "one of the smallest countries"]},
    "81": {"category": "countries", "statement": "Nigeria is the ____ country in Africa.", "answer": "most populous", "options": ["most populous", "second most populous"]},
    "82": {"category": "countries", "statement": "Italy is a major producer of ____.", "answer": "wine", "options": ["wine", "beer"]},
    "83": {"category": "countries", "statement": "Estonia is a ____ country.", "answer": "Baltic", "options": ["Baltic", "Scandinavian"]},
    "84": {"category": "countries", "statement": "Colombia produces the most ____ in the world.", "answer": "emeralds", "options": ["emeralds", "diamonds"]},
    "85": {"category": "countries", "statement": "In Morocco, people do not usually eat ____.", "answer": "pork", "options": ["pork", "beef"]},
    "86": {"category": "countries", "statement": "People in Mozambique speak ____.", "answer": "Portuguese", "options": ["Portuguese", "Spanish"]},
    "87": {"category": "countries", "statement": "Western Sahara is governed by ____.", "answer": "Morocco", "options": ["Morocco", "Algeria"]},
    "88": {"category": "countries", "statement": "Gabon is located in ____.", "answer": "Central Africa", "options": ["Central Africa", "West Africa"]},
    "89": {"category": "countries", "statement": "Tanzania borders ____.", "answer": "Zambia", "options": ["Zambia", "Zimbabwe"]},
    "90": {"category": "countries", "statement": "Spain is a ____ country.", "answer": "Mediterranean", "options": ["Mediterranean", "Atlantic"]},
    "91": {"category": "countries", "statement": "In Spain and Portugal, people do not usually eat a big ____.", "answer": "dinner", "options": ["dinner", "lunch"]},
    "92": {"category": "countries", "statement": "St. Lucia is located in ____.", "answer": "the Caribbean", "options": ["the Caribbean", "the Pacific"]},
    "93": {"category": "countries", "statement": "St. Patrick's Day is a festival celebrated in ____.", "answer": "Ireland", "options": ["Ireland", "Scotland"]},
    "94": {"category": "countries", "statement": "The country with the tallest people is ____.", "answer": "the Netherlands", "options": ["the Netherlands", "Germany"]},
    "95": {"category": "countries", "statement": "Australia is a ____.", "answer": "constitutional monarchy", "options": ["constitutional monarchy", "republic"]},
    "96": {"category": "countries", "statement": "The three top selling authors of all time are from ____.", "answer": "the United Kingdom", "options": ["the United Kingdom", "the United States"]},
    "97": {"category": "countries", "statement": "Hungary is well-known for its ____.", "answer": "goulash", "options": ["goulash", "pies"]},
    "98": {"category": "countries", "statement": "People in the Philippines like to sing ____.", "answer": "karaoke", "options": ["karaoke", "opera"]},
    "99": {"category": "countries", "statement": "Japan is a ____ country.", "answer": "unitary", "options": ["unitary", "federal"]},
    "100": {"category": "countries", "statement": "China is divided into ____.", "answer": "provinces", "options": ["provinces", "states"]}
}


true_or_false_cities = {
    "1": {"category": "cities", "statement": "The capital of the United States is ____.", "answer": "Washington, D.C.", "options": ["Washington, D.C.", "New York City"]},
    "2": {"category": "cities", "statement": "The capital of Australia is ____.", "answer": "Canberra", "options": ["Canberra", "Sydney"]},
    "3": {"category": "cities", "statement": "The capital of Canada is ____.", "answer": "Ottawa", "options": ["Ottawa", "Toronto"]},
    "4": {"category": "cities", "statement": "The capital of Brazil is ____.", "answer": "Brasilia", "options": ["Brasilia", "Rio de Janeiro"]},
    "5": {"category": "cities", "statement": "The most populous city in the Americas is ____.", "answer": "Sao Paulo", "options": ["Sao Paulo", "Mexico City"]},
    "6": {"category": "cities", "statement": "The most populous city in Europe is ____.", "answer": "Istanbul", "options": ["Istanbul", "Moscow"]},
    "7": {"category": "cities", "statement": "Spaccanapoli is a long, straight, narrow street in ____.", "answer": "Naples", "options": ["Naples", "Rome"]},
    "8": {"category": "cities", "statement": "Portugal's second largest city is ____.", "answer": "Porto", "options": ["Porto", "Lisbon"]},
    "9": {"category": "cities", "statement": "Seoul is known for having the most ____ in the world.", "answer": "plastic surgery clinics", "options": ["plastic surgery clinics", "hair salons"]},
    "10": {"category": "cities", "statement": "Nara is an ancient city in ____.", "answer": "Japan", "options": ["Japan", "China"]},
    "11": {"category": "cities", "statement": "It is common to see ____ restaurants in Sao Paulo.", "answer": "Japanese", "options": ["Japanese", "Chinese"]},
    "12": {"category": "cities", "statement": "Cairns is well-known for its close proximity to the ____ rainforest.", "answer": "Daintree", "options": ["Daintree", "Gondwana"]},
    "13": {"category": "cities", "statement": "Paris is known for its ____.", "answer": "cafes", "options": ["cafes", "discos"]},
    "14": {"category": "cities", "statement": "Krakow in the ____ of Poland.", "answer": "south", "options": ["south", "north"]},
    "15": {"category": "cities", "statement": "Pizza was invented in ____.", "answer": "Naples", "options": ["Naples", "Milan"]},
    "16": {"category": "cities", "statement": "Bonn is the former capital of ____.", "answer": "Germany", "options": ["Germany", "Austria"]},
    "17": {"category": "cities", "statement": "The capital of the United Arab Emirates is ____.", "answer": "Abu Dhabi", "options": ["Abu Dhabi", "Dubai"]},
    "18": {"category": "cities", "statement": "The capital of South Africa is ____.", "answer": "Pretoria", "options": ["Pretoria", "Cape Town"]},
    "19": {"category": "cities", "statement": "The capital of New Zealand is ____.", "answer": "Wellington", "options": ["Wellington", "Auckland"]},
    "20": {"category": "cities", "statement": "The most liguistically diverse city in the world is ____.", "answer": "New York City", "options": ["New York City", "London"]},
    "21": {"category": "cities", "statement": "The city of ____ is built on 118 small islands.", "answer": "Venice", "options": ["Venice", "Amsterdam"]},
    "22": {"category": "cities", "statement": "The city of ____ is located in two continents.", "answer": "Istanbul", "options": ["Istanbul", "Moscow"]},
    "23": {"category": "cities", "statement": "Tokyo has the world's busiest ____.", "answer": "pedestrian crossing", "options": ["pedestrian crossing", "airport"]},
    "24": {"category": "cities", "statement": "Miami is known for its ____.", "answer": "beaches", "options": ["beaches", "amusement parks"]},
    "25": {"category": "cities", "statement": "Minnesota is known as the ____ of the United States.", "answer": "land of 10,000 lakes", "options": ["land of 10,000 lakes", "land of 10,000 rivers"]},
    "26": {"category": "cities", "statement": "Salzburg is where the movie ____ was filmed.", "answer": "The Sound of Music", "options": ["The Sound of Music", "The Wizard of Oz"]},
    "27": {"category": "cities", "statement": "The headquarters of the Red Cross is located in ____.", "answer": "Geneva", "options": ["Geneva", "Zurich"]},
    "28": {"category": "cities", "statement": "The Sagrada Familia is located in ____.", "answer": "Barcelona", "options": ["Barcelona", "Madrid"]},
    "29": {"category": "cities", "statement": "Every year ____ holds a carnival, one of the world's most colorful festivals.", "answer": "Rio de Janeiro", "options": ["Rio de Janeiro", "Sao Paulo"]},
    "30": {"category": "cities", "statement": "The city of ____ has more bridges than any other city in the world.", "answer": "Chongqing", "options": ["Chongqing", "Hamburg"]},
    "31": {"category": "cities", "statement": "The city of ____ has more bicycles than people.", "answer": "Amsterdam", "options": ["Amsterdam", "Zurich"]},
    "32": {"category": "cities", "statement": "The city of ____ has more canals than Venice.", "answer": "Stockholm", "options": ["Stockholm", "Amsterdam"]},
    "33": {"category": "cities", "statement": "The city with the most museums in the world is ____.", "answer": "Mexico City", "options": ["Mexico City", "London"]},
    "34": {"category": "cities", "statement": "The city with the most skyscrapers in the world is ____.", "answer": "Hong Kong", "options": ["Hong Kong", "New York City"]},
    "35": {"category": "cities", "statement": "The city with the most billionaires in the world is ____.", "answer": "New York City", "options": ["New York City", "London"]},
    "36": {"category": "cities", "statement": "The city with the most billionaires per capita in the world is ____.", "answer": "Monaco", "options": ["Monaco", "New York City"]},
    "37": {"category": "cities", "statement": "The city with the most expensive real estate in the world is ____.", "answer": "Hong Kong", "options": ["Hong Kong", "London"]},
    "38": {"category": "cities", "statement": "The world's oldest subway system is in ____.", "answer": "London", "options": ["London", "New York City"]},
    "39": {"category": "cities", "statement": "The world's oldest zoo is in ____.", "answer": "Vienna", "options": ["Vienna", "London"]},
    "40": {"category": "cities", "statement": "The world's oldest university is in ____.", "answer": "Bologna", "options": ["Bologna", "Athens"]},
    "41": {"category": "cities", "statement": "The world's oldest restaurant is in ____.", "answer": "Madrid", "options": ["Madrid", "Paris"]},
    "42": {"category": "cities", "statement": "The city of Taal was once the capital of ____.", "answer": "the Philippines", "options": ["the Philippines", "Indonesia"]},
    "43": {"category": "cities", "statement": "The city of Koblenz is located at the confluence of the Rhine and ____ rivers.", "answer": "Moselle", "options": ["Moselle", "Danube"]},
    "44": {"category": "cities", "statement": "Windhoek is the capital of ____.", "answer": "Namibia", "options": ["Namibia", "Botswana"]},
    "45": {"category": "cities", "statement": "The capital city of England was once ____.", "answer": "Winchester", "options": ["Winchester", "Canterbury"]},
    "46": {"category": "cities", "statement": "The metro area population of ____ is around 21 million.", "answer": "Mumbai", "options": ["Mumbai", "Delhi"]},
    "47": {"category": "cities", "statement": "The metro area population of ____ is around 16 million.", "answer": "Kolkata", "options": ["Kolkata", "Delhi"]},
    "48": {"category": "cities", "statement": "Europe's largest free trade port is in ____.", "answer": "Rotterdam", "options": ["Rotterdam", "Hamburg"]},
    "49": {"category": "cities", "statement": "The city of ____ is located in the southernmost part of the United States.", "answer": "Key West", "options": ["Key West", "Miami"]},
    "50": {"category": "cities", "statement": "The world's largest indoor escalator is in ____.", "answer": "Hong Kong", "options": ["Hong Kong", "New York City"]},
    "51": {"category": "cities", "statement": "The most densely populated city in the world is ____.", "answer": "Manila", "options": ["Manila", "Singapore"]},
    "52": {"category": "cities", "statement": "The most populous city in the world by metro population is ____.", "answer": "Tokyo", "options": ["Tokyo", "Shanghai"]},
    "53": {"category": "cities", "statement": "In ____ it is illegal to die.", "answer": "Longyearbyen", "options": ["Longyearbyen", "Reykjavik"]},
    "54": {"category": "cities", "statement": "In ____ it is illegal to mow your lawn on a Sunday.", "answer": "Switzerland", "options": ["Switzerland", "the United Kingdom"]},
    "55": {"category": "cities", "statement": "The old town of ____ features a 14th century astronomical clock.", "answer": "Prague", "options": ["Prague", "Vienna"]},
    "56": {"category": "cities", "statement": "The city of ____ is located on the island of Java.", "answer": "Jakarta", "options": ["Jakarta", "Kuala Lumpur"]},
    "57": {"category": "cities", "statement": "The city of ____ is located on the island of Borneo.", "answer": "Kuching", "options": ["Kuching", "Kuala Lumpur"]},
    "58": {"category": "cities", "statement": "Oktoberfest is held in ____.", "answer": "Munich", "options": ["Munich", "Berlin"]},
    "59": {"category": "cities", "statement": "The croissant was invented in ____.", "answer": "Vienna", "options": ["Vienna", "Paris"]},
    "60": {"category": "cities", "statement": "Mt. Vesuvius is located near the city of ____.", "answer": "Naples", "options": ["Naples", "Rome"]},
    "61": {"category": "cities", "statement": "Mt. Etna is located near the city of ____.", "answer": "Catania", "options": ["Catania", "Palermo"]},
    "62": {"category": "cities", "statement": "Guangzhou is the capital of ____ province.", "answer": "Guangdong", "options": ["Guangdong", "Guangxi"]},
    "63": {"category": "cities", "statement": "The capital of ____ is the highest capital city in the world.", "answer": "Bolivia", "options": ["Bolivia", "Peru"]},
    "64": {"category": "cities", "statement": "Shenzhen has the world's largest ____.", "answer": "electronics market", "options": ["electronics market", "flea market"]},
    "65": {"category": "cities", "statement": "Tashkent is the capital of ____.", "answer": "Uzbekistan", "options": ["Uzbekistan", "Kazakhstan"]},
    "66": {"category": "cities", "statement": "Cebu is the oldest city in ____.", "answer": "the Philippines", "options": ["the Philippines", "Indonesia"]},
    "67": {"category": "cities", "statement": "Bucharest has the world's largest ____.", "answer": "parliament building", "options": ["parliament building", "library"]},
    "68": {"category": "cities", "statement": "Hobart is the capital of ____.", "answer": "Tasmania", "options": ["Tasmania", "New Zealand"]},
    "69": {"category": "cities", "statement": "Mardi Gras is held in ____.", "answer": "New Orleans", "options": ["New Orleans", "Rio de Janeiro"]},
    "70": {"category": "cities", "statement": "Segovia is known for its ____.", "answer": "aqueduct", "options": ["aqueduct", "castle"]},
    "71": {"category": "cities", "statement": "Orlando is known for its ____.", "answer": "amusement parks", "options": ["amusement parks", "beaches"]},
    "72": {"category": "cities", "statement": "Every year, the Notting Hill Carnival is held in ____.", "answer": "London", "options": ["London", "Nottingham"]},
    "73": {"category": "cities", "statement": "Busan is the ____ largest city in South Korea.", "answer": "second", "options": ["second", "third"]},
    "74": {"category": "cities", "statement": "The city of ____ is located on the island of Hokkaido.", "answer": "Sapporo", "options": ["Sapporo", "Osaka"]},
    "75": {"category": "cities", "statement": "The largest port city in the world is ____.", "answer": "Shanghai", "options": ["Shanghai", "Hong Kong"]},
    "76": {"category": "cities", "statement": "The city of ____ is located on the island of Luzon.", "answer": "Manila", "options": ["Manila", "Cebu"]},
    "77": {"category": "cities", "statement": "Santiago has the tallest ____ in South America.", "answer": "skyscraper", "options": ["skyscraper", "church"]},
    "78": {"category": "cities", "statement": "Fontana di Trevi is located in ____.", "answer": "Rome", "options": ["Rome", "Florence"]},
    "79": {"category": "cities", "statement": "Stockholm is known for its ____.", "answer": "subway art", "options": ["subway art", "fancy restaurants"]},
    "80": {"category": "cities", "statement": "Copacabana Beach is located in ____.", "answer": "Rio de Janeiro", "options": ["Rio de Janeiro", "Sao Paulo"]},
    "81": {"category": "cities", "statement": "Montevideo is the capital of ____.", "answer": "Uruguay", "options": ["Uruguay", "Paraguay"]},
    "82": {"category": "cities", "statement": "The Summer Palace is located in ____.", "answer": "Beijing", "options": ["Beijing", "Shanghai"]},
    "83": {"category": "cities", "statement": "The Forbidden City is located in ____.", "answer": "Beijing", "options": ["Beijing", "Shanghai"]},
    "84": {"category": "cities", "statement": "The city of Verona is known for being the setting of ____.", "answer": "Romeo and Juliet", "options": ["Romeo and Juliet", "Hamlet"]},
    "85": {"category": "cities", "statement": "The capital city of Latvia is ____.", "answer": "Riga", "options": ["Riga", "Vilnius"]},
    "86": {"category": "cities", "statement": "Bergen is in the ____ of Norway.", "answer": "southwest", "options": ["southwest", "southeast"]},
    "87": {"category": "cities", "statement": "Bergen is known for its ____.", "answer": "rain", "options": ["rain", "snow"]},
    "88": {"category": "cities", "statement": "San Francisco is known for its ____.", "answer": "fog", "options": ["fog", "rain"]},
    "89": {"category": "cities", "statement": "Chicago is known for its ____.", "answer": "wind", "options": ["wind", "rain"]},
    "90": {"category": "cities", "statement": "Denver is the capital of ____.", "answer": "Colorado", "options": ["Colorado", "Utah"]},
    "91": {"category": "cities", "statement": "The capital city of the US state of Alabama is ____.", "answer": "Montgomery", "options": ["Montgomery", "Birmingham"]},
    "92": {"category": "cities", "statement": "The capital city of the US state of Alaska is ____.", "answer": "Juneau", "options": ["Juneau", "Anchorage"]},
    "93": {"category": "cities", "statement": "The biggest port in South America is in ____.", "answer": "Santos", "options": ["Santos", "Rio de Janeiro"]},
    "94": {"category": "cities", "statement": "The biggest port in Africa is in ____.", "answer": "Durban", "options": ["Durban", "Cape Town"]},
    "95": {"category": "cities", "statement": "Alexandria is famous for its ____.", "answer": "lighthouse", "options": ["lighthouse", "pyramids"]},
    "96": {"category": "cities", "statement": "The capital of the US state of California is ____.", "answer": "Sacramento", "options": ["Sacramento", "Los Angeles"]},
    "97": {"category": "cities", "statement": "The Taj Mahal is located in ____.", "answer": "Agra", "options": ["Agra", "Jaipur"]},
    "98": {"category": "cities", "statement": "Angkor Wat is located in the Cambodian city of ____.", "answer": "Siem Reap", "options": ["Siem Reap", "Phnom Penh"]},
    "99": {"category": "cities", "statement": "The Burj Khalifa is located in ____.", "answer": "Dubai", "options": ["Dubai", "Abu Dhabi"]},
    "100": {"category": "cities", "statement": "The capital of the US state of Florida is ____.", "answer": "Tallahassee", "options": ["Tallahassee", "Miami"]}
}


true_or_false_food = {
    "1": {"category": "food", "statement": "The national dish of the United States is ____.", "answer": "hamburger", "options": ["hamburger", "hot dog"]},
    "2": {"category": "food", "statement": "The only food that does not spoil is ____.", "answer": "honey", "options": ["honey", "maple syrup"]},
    "3": {"category": "food", "statement": "Strawberries are not a kind of ____.", "answer": "berry", "options": ["berry", "fruit"]},
    "4": {"category": "food", "statement": "The most popular vegetable in the world is the ____.", "answer": "tomato", "options": ["tomato", "potato"]},
    "5": {"category": "food", "statement": "The most popular fruit in the world is the ____.", "answer": "banana", "options": ["banana", "apple"]},
    "6": {"category": "food", "statement": "Raw ____ are poisonous.", "answer": "cashews", "options": ["cashews", "peanuts"]},
    "7": {"category": "food", "statement": "Blackcurrants are very high in ____.", "answer": "vitamin C", "options": ["vitamin C", "vitamin E"]},
    "8": {"category": "food", "statement": "Some vanilla substitutes come from ____.", "answer": "beaver anal glands", "options": ["beaver anal glands", "beaver urine"]},
    "9": {"category": "food", "statement": "The most popular cheese in the world is ____.", "answer": "mozzarella", "options": ["mozzarella", "cheddar"]},
    "10": {"category": "food", "statement": "Tomatoes only came to Europe in the ____ century.", "answer": "16th", "options": ["16th", "17th"]},
    "11": {"category": "food", "statement": "The most popular grain in the world is ____.", "answer": "rice", "options": ["rice", "wheat"]},
    "12": {"category": "food", "statement": "Cinnamon is made from ____.", "answer": "tree bark", "options": ["tree bark", "tree sap"]},
    "13": {"category": "food", "statement": "Wild ____ are common in the United States.", "answer": "blueberries", "options": ["blueberries", "oranges"]},
    "14": {"category": "food", "statement": "Wild ____ are common in the United Kingdom.", "answer": "blackberries", "options": ["blackberries", "grapes"]},
    "15": {"category": "food", "statement": "Apples float in water because they are ____ percent air.", "answer": "25", "options": ["25", "50"]},
    "16": {"category": "food", "statement": "The world's most expensive spice is ____.", "answer": "saffron", "options": ["saffron", "vanilla"]},
    "17": {"category": "food", "statement": "The world's most consumed meat is ____.", "answer": "pork", "options": ["pork", "beef"]},
    "18": {"category": "food", "statement": "The world's most consumed seafood is ____.", "answer": "shrimp", "options": ["shrimp", "salmon"]},
    "19": {"category": "food", "statement": "Potatoes contain a toxin called ____.", "answer": "solanine", "options": ["solanine", "nicotine"]},
    "20": {"category": "food", "statement": "The world's most expensive coffee is made from ____.", "answer": "civet poop", "options": ["civet poop", "elephant poop"]},
    "21": {"category": "food", "statement": "The ____ fruit is banned in many hotels.", "answer": "durian", "options": ["durian", "jackfruit"]},
    "22": {"category": "food", "statement": "French fries actually originated in ____.", "answer": "Belgium", "options": ["Belgium", "France"]},
    "23": {"category": "food", "statement": "Popcorn was first invented 9,000 years ago in ____.", "answer": "Mexico", "options": ["Mexico", "Peru"]},
    "24": {"category": "food", "statement": "Leeks are a kind of ____.", "answer": "onion", "options": ["onion", "garlic"]},
    "25": {"category": "food", "statement": "Popcorn kernals can pop up to ____ in the air.", "answer": "a meter", "options": ["a meter", "two meters"]},
    "26": {"category": "food", "statement": "In 1995, the ____ became the first vegetable to be grown in space.", "answer": "potato", "options": ["potato", "tomato"]},
    "27": {"category": "food", "statement": "The first version of Ketchup was made from ____.", "answer": "pickled fish", "options": ["pickled fish", "pickled onions"]},
    "28": {"category": "food", "statement": "Ketchup was once sold as ____.", "answer": "medicine", "options": ["medicine", "meal replacement"]},
    "29": {"category": "food", "statement": "There are more than ____ varieties of cheese in the world.", "answer": "2,000", "options": ["2,000", "4,000"]},
    "30": {"category": "food", "statement": "There are more than ____ varieties of apples in the world.", "answer": "7,500", "options": ["7,500", "10,000"]},
    "31": {"category": "food", "statement": "There are more than ____ varieties of potatoes in the world.", "answer": "4,000", "options": ["4,000", "7,000"]},
    "32": {"category": "food", "statement": "The biggest apple ever picked weighed ____ kilograms.", "answer": "1.8", "options": ["1.8", "2.8"]},
    "33": {"category": "food", "statement": "The biggest pumpkin ever picked weighed ____ kilograms.", "answer": "1,190", "options": ["1,190", "690"]},
    "34": {"category": "food", "statement": "The biggest watermelon ever picked weighed ____ kilograms.", "answer": "159", "options": ["159", "259"]},
    "35": {"category": "food", "statement": "The biggest carrot ever picked weighed ____ kilograms.", "answer": "10", "options": ["10", "20"]},
    "36": {"category": "food", "statement": "The biggest cabbage ever picked weighed ____ kilograms.", "answer": "62", "options": ["62", "32"]},
    "37": {"category": "food", "statement": "Peanuts are more closely related to ____ than nuts.", "answer": "beans", "options": ["beans", "seeds"]},
    "38": {"category": "food", "statement": "Carrots were originally ____ in color.", "answer": "purple", "options": ["purple", "yellow"]},
    "39": {"category": "food", "statement": "Pineapples take on average ____ months to grow.", "answer": "18", "options": ["22", "14"]},
    "40": {"category": "food", "statement": "The first soup was likely made from ____.", "answer": "hippopotamus", "options": ["hippopotamus", "elephant"]},
    "41": {"category": "food", "statement": "Square watermelons are grown in ____.", "answer": "Japan", "options": ["Japan", "China"]},
    "42": {"category": "food", "statement": "Spicy food is known to ____.", "answer": "increase metabolism", "options": ["increase metabolism", "decrease metabolism"]},
    "43": {"category": "food", "statement": "Scicy food can ____.", "answer": "cool you down", "options": ["cool you down", "warm you up"]},
    "44": {"category": "food", "statement": "Coffee was originally ____.", "answer": "chewed", "options": ["chewed", "smoked"]},
    "45": {"category": "food", "statement": "Around ____ percent of the world's population is lactose intolerant.", "answer": "65", "options": ["65", "45"]},
    "46": {"category": "food", "statement": "Around ____ percent of the world's population is allergic to peanuts.", "answer": "1", "options": ["1", "5"]},
    "47": {"category": "food", "statement": "Around 80% of the world's almonds are grown in ____.", "answer": "California", "options": ["California", "Mexico"]},
    "48": {"category": "food", "statement": "Potatoes can absorb and reflect ____.", "answer": "radio waves", "options": ["radio waves", "microwaves"]},
    "49": {"category": "food", "statement": "Frozen vegetables are usually ____ than fresh vegetables.", "answer": "more nutritious", "options": ["more nutritious", "less nutritious"]},
    "50": {"category": "food", "statement": "A cluster of bananas is called a ____.", "answer": "hand", "options": ["hand", "bunch"]},
    "51": {"category": "food", "statement": "Almonds are part of the ____ family.", "answer": "peach", "options": ["peach", "apple"]},
    "52": {"category": "food", "statement": "Eating cucumbers can help ____.", "answer": "reduce bad breath", "options": ["reduce bad breath", "reduce body odor"]},
    "53": {"category": "food", "statement": "Tomatoes have around 31,000 different ____ - more than humans.", "answer": "genes", "options": ["genes", "chromosomes"]},
    "54": {"category": "food", "statement": "In the UK, white chocolate must contain ____ to be considered chocolate.", "answer": "at least 14% milk", "options": ["at least 14% milk", "at least 14% cream"]},
    "55": {"category": "food", "statement": "Insects are a common snack in ____.", "answer": "Thailand", "options": ["Thailand", "France"]},
    "56": {"category": "food", "statement": "Humans share ____ percent of their DNA with bananas.", "answer": "50", "options": ["50", "60"]},
    "57": {"category": "food", "statement": "Chocolate melts at around ____ degrees Celsius.", "answer": "34", "options": ["34", "44"]},
    "58": {"category": "food", "statement": "Honey comes from ____.", "answer": "bee vomit", "options": ["bee vomit", "bee poop"]},
    "59": {"category": "food", "statement": "The ancient Egyptians used ____ as a form of currency.", "answer": "bread", "options": ["bread", "rice"]},
    "60": {"category": "food", "statement": "The ancient Romans used ____ as a form of currency.", "answer": "salt", "options": ["salt", "pepper"]},
    "61": {"category": "food", "statement": "The ancient Aztecs used ____ as a form of currency.", "answer": "cocoa beans", "options": ["cocoa beans", "coffee beans"]},
    "62": {"category": "food", "statement": ""}

}