"""empty message

Revision ID: 150dbf30852e
Revises: c04a5da1c2b9
Create Date: 2024-01-25 22:45:50.306842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150dbf30852e'
down_revision = 'c04a5da1c2b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('high_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('high_score', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
