"""empty message

Revision ID: 274f366d29b3
Revises: 93e859b4c848
Create Date: 2024-02-01 16:03:07.807714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274f366d29b3'
down_revision = '93e859b4c848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index('ix_logs_unique_id')
        batch_op.create_index(batch_op.f('ix_logs_unique_id'), ['unique_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logs_unique_id'))
        batch_op.create_index('ix_logs_unique_id', ['unique_id'], unique=False)

    # ### end Alembic commands ###
