"""empty message

Revision ID: 4af91c49ef56
Revises: 758b2510061b
Create Date: 2024-02-02 22:59:57.223938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af91c49ef56'
down_revision = '758b2510061b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_id', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.drop_column('issue_id')

    # ### end Alembic commands ###
