"""empty message

Revision ID: 65c12efcfb95
Revises: 1ff124181d93
Create Date: 2024-02-01 10:55:59.995980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c12efcfb95'
down_revision = '1ff124181d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_column('info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
