"""empty message

Revision ID: 758b2510061b
Revises: 274f366d29b3
Create Date: 2024-02-02 18:35:58.045449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758b2510061b'
down_revision = '274f366d29b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unique_id', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_column('unique_id')

    # ### end Alembic commands ###
