"""Initial migration

Revision ID: 76a70fc51be7
Revises: 633c85c67297
Create Date: 2023-12-09 22:28:03.036558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '76a70fc51be7'
down_revision = '633c85c67297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hashed', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('games_played', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('games_tracker', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('games_tracker')
        batch_op.drop_column('games_played')
        batch_op.drop_column('password_hashed')

    # ### end Alembic commands ###
