"""empty message

Revision ID: ab0f089b3297
Revises: b47b0fd4bbf3
Create Date: 2024-02-25 13:11:03.174115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0f089b3297'
down_revision = 'b47b0fd4bbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_logs', schema=None) as batch_op:
        batch_op.drop_column('game_name')

    # ### end Alembic commands ###
