"""empty message

Revision ID: c79630ac43d9
Revises: ab0f089b3297
Create Date: 2024-02-25 14:40:07.589745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79630ac43d9'
down_revision = 'ab0f089b3297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seconds_to_answer', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_logs', schema=None) as batch_op:
        batch_op.drop_column('seconds_to_answer')

    # ### end Alembic commands ###
